-- Autogenerated with DRAKON Editor 1.32
require('strict').on()

local table = table
local string = string
local pairs = pairs
local ipairs = ipairs
local io = io
local pcall = pcall
local xpcall = xpcall
local debug = debug
local math = math
local tostring = tostring
local tonumber = tonumber
local clock = require("clock")
local log = require("log")
local digest = require("digest")
local fiber = require("fiber")
local json = require("json")
local fio = require("fio")
local log = require("log")
local os = os
local error = error
local print = print

local utf8 = require("lua-utf8")

local utils = require("utils")
local ej = require("ej")
local space = require("space")
local box = box

-- configuration
local global_cfg = global_cfg

setfenv(1, {}) 

local module = {}

module.handlers = {}



function add_to_recent(doc_id, user_id)
    local fields, i, key, max_recent, now, recent, recent_row, row, to_kill
    -- item 336
    now = utils.utc_time()
    -- item 335
    fields = {
        timestamp = now
    }
    -- item 337
    row = {doc_id, user_id, fields}
    -- item 338
    box.space.rrecent:replace(row)
    -- item 374
    max_recent = 30
    -- item 377
    recent = db_recent_by_user(user_id)
    -- item 379
    to_kill = #recent - max_recent
    -- item 380
    if to_kill > 0 then
        -- item 378
        utils.sort_by_prop(recent, "timestamp", "asc")
        -- item 3830001
        i = 1
        while true do
            -- item 3830002
            if i <= to_kill then
                
            else
                break
            end
            -- item 385
            recent_row = recent[i]
            key = {recent_row.doc_id, recent_row.user_id}
            -- item 386
            box.space.rrecent:delete(key)
            -- item 3830003
            i = i + 1
        end
    end
end

function api(data, user_id, roles)
    local handler, ok, op, output_data
    -- item 38
    if data then
        -- item 42
        op = data.op
        -- item 47
        if op then
            -- item 37
            handler = module.handlers[op]
            -- item 34
            if handler then
                -- item 45
                ok, output_data = handler(
                    data.body,
                    user_id,
                    roles
                )
            else
                -- item 43
                ok = false
                output_data = "ERR_NOT_FOUND"
            end
        else
            -- item 41
            ok = false
            output_data = "ERR_BAD_REQUEST"
        end
    else
        -- item 41
        ok = false
        output_data = "ERR_BAD_REQUEST"
    end
    -- item 1157
    if ok then
        -- item 18
        return ok, {data=output_data}
    else
        -- item 1160
        return false, output_data
    end
end

function can_write(doc_id, user_id, roles)
    local can, space_id
    -- item 169
    space_id = db_get_doc_space(
        doc_id
    )
    -- item 799
    can = can_write_to_space(
        space_id,
        user_id,
        roles
    )
    -- item 178
    return can, space_id
end

function can_write_to_space(space_id, user_id, roles)
    local access
    -- item 787
    access = space.get_space_access(
        space_id,
        user_id,
        roles
    )
    -- item 7880001
    if (access == "write") or (access == "admin") then
        -- item 795
        return true, space_id
    else
        -- item 796
        return false
    end
end

function copy(data, user_id, roles)
    local ok, result, tags, target_space
    -- item 818
    ok, target_space = can_write(
        data.target,
        user_id,
        roles
    )
    -- item 819
    result = nil
    -- item 815
    if ok then
        local normal_827
        normal_827 = 1
        for _, doc_id in ipairs(data.docs) do
            -- item 830
            if find_cycle(doc_id, data.target) then
                -- item 832
                ok = false
                result = "ERR_CYCLE"
                normal_827 = 0
                break
            end
        end
        if normal_827 == 1 then
            -- item 910
            tags = {}
            -- item 924
            tags[data.target] = tag_doc(
                data.target,
                user_id
            )
            for _, doc_id in ipairs(data.docs) do
                -- item 836
                db_copy_doc(
                    doc_id,
                    data.target,
                    tags,
                    user_id
                )
            end
            -- item 907
            result = {tags=tags}
        end
    else
        -- item 820
        ok = false
        result = "ERR_ACCESS_DENIED"
    end
    -- item 821
    return ok, result
end

function create_root_folder(space_id, user_id)
    local fields, id
    -- item 65
    fields = {
        type = "folder"
    }
    -- item 66
    set_when_created(fields, user_id)
    -- item 607
    id = generate_doc_id()
    -- item 608
    box.space.rtags:insert {
    	id,
    	space_id,
    	1,
    	true
    }
    -- item 609
    box.space.rdocs:insert {
    	id,
    	"",
    	fields
    }
    -- item 610
    return id
end

function db_copy_doc(old_doc_id, parent_id, tags, user_id)
    local child_id, children, doc, doc_id, fields, item_body, item_id, items, space_id, tag
    -- item 922
    box.begin()
    -- item 916
    doc = db_get_doc(old_doc_id)
    -- item 918
    space_id = db_get_doc_space(parent_id)
    -- item 917
    fields = doc[3]
    -- item 911
    set_when_updated(fields, user_id)
    -- item 912
    doc_id, tag = db_insert_doc(
        space_id,
        parent_id,
        fields
    )
    -- item 914
    tags[doc_id] = tag
    -- item 925
    items = db_get_items(old_doc_id)
    for _, item in ipairs(items) do
        -- item 929
        item_id = item[2]
        item_body = item[3]
        -- item 928
        db_insert_item(
            doc_id,
            item_id,
            item_body
        )
    end
    -- item 923
    box.commit()
    -- item 930
    children = db_get_doc_children(old_doc_id)
    for _, child in ipairs(children) do
        -- item 933
        child_id = child[1]
        -- item 934
        db_copy_doc(
            child_id,
            doc_id,
            tags,
            user_id
        )
    end
end

function db_delete_doc(doc_id)
    local child_id, children, recent
    -- item 240
    children = db_get_doc_children(
        doc_id
    )
    for _, child in ipairs(children) do
        -- item 245
        child_id = child[1]
        -- item 243
        db_delete_doc(child_id)
    end
    -- item 453
    db_delete_items(doc_id)
    -- item 454
    recent = db_recent_rows_by_doc(doc_id)
    -- item 455
    db_delete_recent(recent)
    -- item 713
    tag_update(doc_id, false)
    -- item 221
    return box.space.rdocs:delete(doc_id)
end

function db_delete_item(doc_id, item_id)
    local key
    -- item 512
    key = {doc_id, item_id}
    -- item 513
    box.space.ritems:delete(key)
end

function db_delete_items(doc_id)
    local item_rows, key
    -- item 441
    item_rows = db_get_items(doc_id)
    for _, row in ipairs(item_rows) do
        -- item 444
        key = make_key2(row)
        -- item 452
        box.space.ritems:delete(key)
    end
end

function db_delete_recent(rows)
    local key
    for _, row in ipairs(rows) do
        -- item 405
        key = {row[1], row[2]}
        -- item 406
        box.space.rrecent:delete(key)
    end
end

function db_get_doc(doc_id)
    -- item 79
    return box.space.rdocs:get(doc_id)
end

function db_get_doc_children(doc_id)
    -- item 244
    return box.space.rdocs.index.by_parent:select(doc_id)
end

function db_get_doc_children_rec(doc_id, output)
    local child_id, docs
    -- item 579
    docs = db_get_doc_children(doc_id)
    -- item 580
    utils.add_range(output, docs)
    for _, doc in ipairs(docs) do
        -- item 583
        child_id = doc[1]
        -- item 584
        db_get_doc_children_rec(
            child_id,
            output
        )
    end
end

function db_get_doc_space(doc_id)
    local row
    -- item 611
    row = box.space.rtags:get(doc_id)
    -- item 612
    return row[2]
end

function db_get_docs(space_id)
    local result, root, row, sdata
    -- item 573
    row = box.space.spaces:get(space_id)
    -- item 585
    if row then
        -- item 589
        sdata = row[2]
        -- item 590
        if utils.is_empty(sdata.root_id) then
            -- item 588
            return {}
        else
            -- item 593
            root = db_get_doc(sdata.root_id)
            -- item 591
            result = {root}
            -- item 594
            db_get_doc_children_rec(
                sdata.root_id,
                result
            )
            -- item 592
            return result
        end
    else
        -- item 588
        return {}
    end
end

function db_get_items(doc_id)
    -- item 434
    return box.space.ritems:select(doc_id)
end

function db_get_tag_row(doc_id)
    -- item 681
    return box.space.rtags:get(doc_id)
end

function db_insert_doc(space_id, parent_id, fields)
    local doc_id, latest_tag, tag
    -- item 621
    doc_id = generate_doc_id()
    -- item 638
    latest_tag = get_latest_tag(space_id)
    -- item 639
    if latest_tag then
        -- item 642
        tag = latest_tag + 1
    else
        -- item 643
        tag = 1
    end
    -- item 622
    box.space.rtags:insert {
    	doc_id,
    	space_id,
    	tag,
    	true
    }
    -- item 623
    box.space.rdocs:insert {
    	doc_id,
    	parent_id,
    	fields
    }
    -- item 624
    return doc_id, tag
end

function db_insert_item(doc_id, item_id, fields)
    local row
    -- item 519
    row = {
    	doc_id,
    	item_id,
    	fields
    }
    -- item 520
    box.space.ritems:insert(row)
end

function db_move_doc(doc_id, parent_id, tags, user_id)
    local doc, fields, new_row, old_parent
    -- item 960
    box.begin()
    -- item 954
    doc = db_get_doc(doc_id)
    -- item 955
    old_parent = doc[2]
    fields = doc[3]
    -- item 975
    if old_parent == parent_id then
        
    else
        -- item 951
        set_when_updated(fields, user_id)
        -- item 974
        tags[doc_id] = tag_update(doc_id, true)
        tags[old_parent] = tag_doc(old_parent, user_id)
        -- item 972
        new_row = {
        	doc_id,
        	parent_id,
        	fields
        }
        -- item 973
        box.space.rdocs:replace(new_row)
    end
    -- item 961
    box.commit()
end

function db_recent_by_user(user_id)
    local rows
    -- item 414
    rows = db_recent_rows_by_user(
        user_id
    )
    -- item 366
    return utils.map(row_to_recent)
end

function db_recent_rows_by_doc(doc_id)
    -- item 420
    return box.space.rrecent:select(
        doc_id
    )
end

function db_recent_rows_by_user(user_id)
    -- item 413
    return box.space.rrecent.index.by_user:select(
        user_id
    )
end

function db_update_doc(doc_id, fields, user_id)
    local changed_fields, data, new_row, ok, old_row, parent_id, tags
    -- item 662
    ok = true
    data = nil
    -- item 323
    tags = {}
    -- item 259
    old_row = db_get_doc(doc_id)
    -- item 260
    if old_row then
        -- item 268
        changed_fields = old_row[3]
        -- item 269
        utils.copy_props(
            fields,
            changed_fields
        )
        -- item 667
        if fields.parent_id then
            -- item 670
            parent_id = fields.parent_id
        else
            -- item 272
            parent_id = old_row[2]
        end
        -- item 264
        changed_fields.parent_id = nil
        changed_fields.doc_id = nil
        -- item 289
        set_when_updated(changed_fields, user_id)
        -- item 666
        tags[doc_id] = tag_update(doc_id, true)
        tags[parent_id] = tag_doc(parent_id, user_id)
        -- item 265
        new_row = {
        	doc_id,
        	parent_id,
        	changed_fields
        }
        -- item 266
        box.space.rdocs:replace(new_row)
        -- item 267
        ok = true
        data = {tags=tags}
    else
        -- item 263
        ok = false
        data = "ERR_NOT_FOUND"
    end
    -- item 663
    return ok, data
end

function db_update_item(doc_id, item_id, fields)
    local db_fields, key, old_row, row
    -- item 546
    key = {doc_id, item_id}
    -- item 528
    old_row = box.space.ritems:get(key)
    -- item 530
    db_fields = old_row[3]
    -- item 531
    utils.copy_props(
        fields,
        db_fields
    )
    -- item 526
    row = {
    	doc_id,
    	item_id,
    	db_fields
    }
    -- item 527
    box.space.ritems:replace(row)
end

function delete_doc(data, user_id, roles)
    local doc_row, ok, parent_id, result, tag, tags
    -- item 698
    box.begin()
    -- item 202
    if can_write(data.doc_id, user_id, roles) then
        -- item 294
        doc_row = db_get_doc(data.doc_id)
        -- item 207
        db_delete_doc(
            data.doc_id
        )
        -- item 293
        parent_id = doc_row[2]
        -- item 322
        tag = tag_doc(parent_id, user_id)
        tags = {}
        tags[parent_id] = tag
        -- item 208
        ok = true
        result = {tags=tags}
    else
        -- item 205
        ok = false
        result = "ERR_ACCESS_DENIED"
    end
    -- item 699
    box.commit()
    -- item 206
    return ok, result
end

function delete_recent_by_user(user_id)
    local rows
    -- item 394
    rows = db_recent_rows_by_user(
        user_id
    )
    -- item 407
    db_delete_recent(rows)
end

function download_table_rows(doc_id, user_id, roles)
    local by_item_id, items, lines, ok, result
    -- item 1118
    ok, result = get_doc_kernel(
        doc_id,
        user_id,
        roles
    )
    -- item 1123
    if ok then
        -- item 1140
        items = db_get_items(
            doc_id
        )
        -- item 1149
        by_item_id = make_num_comparer(2)
        -- item 1150
        table.sort(items, by_item_id)
        -- item 1141
        lines = utils.map(
            items,
            export_table_row
        )
        -- item 1142
        result = utils.join(lines, "\n")
    end
    -- item 1117
    return ok, result
end

function edit(data, user_id, roles)
    local db_fields, field_names, new_row, ok, old_row, parent_id, ptag, result, tag, tag_row, tags
    local _sw4910000_ = 0
    -- item 715
    box.begin()
    -- item 499
    old_row = db_get_doc(data.doc_id)
    -- item 533
    if old_row then
        -- item 467
        if can_write(data.doc_id, user_id, roles) then
            -- item 532
            parent_id = old_row[2]
            db_fields = old_row[3]
            tag_row = db_get_tag_row(data.doc_id)
            tag = tag_row[3]
            -- item 500
            if tag == data.tag then
                -- item 478
                field_names = utils.set_to_list(
                    data.fields
                )
                -- item 538
                tags = {}
                -- item 479
                if #field_names == 0 then
                    
                else
                    -- item 537
                    utils.copy_props(
                        data.fields,
                        db_fields
                    )
                    -- item 542
                    ptag = tag_doc(parent_id, user_id)
                    tags[parent_id] = ptag
                end
                -- item 543
                set_when_updated(db_fields, user_id)
                -- item 714
                tags[data.doc_id] = tag_update(
                    data.doc_id,
                    true
                )
                -- item 539
                new_row = {
                	data.doc_id,
                	parent_id,
                	db_fields
                }
                -- item 540
                box.space.rdocs:replace(new_row)
                -- item 544
                ok = true
                result = {tags=tags}
                for _, item_edit in ipairs(data.items) do
                    -- item 4910000
                    _sw4910000_ = item_edit.op
                    -- item 4910001
                    if _sw4910000_ == "insert" then
                        -- item 504
                        db_insert_item(
                            data.doc_id,
                            item_edit.id,
                            item_edit.fields
                        )
                    else
                        -- item 4910002
                        if _sw4910000_ == "update" then
                            -- item 505
                            db_update_item(
                                data.doc_id,
                                item_edit.id,
                                item_edit.fields
                            )
                        else
                            -- item 4910003
                            if _sw4910000_ == "delete" then
                                
                            else
                                -- item 4910004
                                error(_sw4910000_)
                            end
                            -- item 506
                            db_delete_item(
                                data.doc_id,
                                item_edit.id
                            )
                        end
                    end
                end
            else
                -- item 503
                ok = false
                result = "ERR_MODIFIED"
            end
        else
            -- item 470
            ok = false
            result = "ERR_ACCESS_DENIED"
        end
    else
        -- item 536
        ok = false
        result = "ERR_NOT_FOUND"
    end
    -- item 716
    box.commit()
    -- item 474
    return ok, result
end

function export_table_row(item_row)
    local body, row
    -- item 1137
    body = item_row[3]
    row = body.row or {}
    -- item 1139
    return utils.join(row, "|")
end

function find_cycle(from_id, to_id)
    local current, current_id, parent_id
    -- item 881
    current_id = to_id
    while true do
        -- item 882
        current = db_get_doc(current_id)
        -- item 886
        parent_id = current[2]
        -- item 883
        if parent_id == "" then
            -- item 887
            return false
        end
        -- item 888
        if parent_id == from_id then
            -- item 889
            return true
        end
        -- item 890
        current_id = parent_id
    end
end

function generate_doc_id()
    local rtags
    -- item 603
    rtags = box.space.rtags
    -- item 598
    local id
    while true do
        -- item 599
        id = utils.random_password(6)
        -- item 600
        local row = rtags:get(id)
        -- item 601
        if row then
            
        else
            break
        end
    end
    -- item 604
    return id
end

function get_all_live_tags(data, user_id, roles)
    local access, item, live, next_cookie, ok, result, rows, rtags, tags
    -- item 725
    access = space.get_space_access(
        data.space_id,
        user_id,
        roles
    )
    -- item 726
    if access then
        -- item 729
        tags = {}
        -- item 733
        rtags = box.space.rtags
        -- item 722
        rows = rtags.index.by_tag:select(
            data.space_id
        )
        for _, row in ipairs(rows) do
            -- item 734
            live = row[4]
            -- item 735
            if live then
                -- item 738
                item = {
                    doc_id = row[1],
                    tag = row[3]
                }
                -- item 739
                table.insert(
                    tags,
                    item
                )
            end
        end
        -- item 771
        next_cookie = get_latest_tag(data.space_id)
        -- item 740
        ok = true
        result = {
        	tags=tags,
        	next_cookie = next_cookie
        }
    else
        -- item 728
        ok = false
        result = "ERR_ACCESS_DENIED"
    end
    -- item 741
    return ok, result
end

function get_changes(data, user_id, roles)
    local access, doc_id, live, next_cookie, ok, result, rtags, tag, tags
    -- item 748
    access = space.get_space_access(
        data.space_id,
        user_id,
        roles
    )
    -- item 749
    if access then
        -- item 752
        tags = {}
        -- item 756
        rtags = box.space.rtags
        -- item 774
        for it, row in rtags.index.by_tag:pairs(
          {data.space_id, data.cookie},
          {iterator="GT"}) do
            if row[2] ~= data.space_id then
                break
            end
        
            local item = {
                doc_id = row[1],
                tag = row[3],
                live = row[4]
            }
        
            table.insert(
                tags,
                item
            )
        end
        -- item 773
        next_cookie = get_latest_tag(data.space_id)
        -- item 772
        ok = true
        result = {
        	tags=tags,
        	next_cookie = next_cookie
        }
    else
        -- item 751
        ok = false
        result = "ERR_ACCESS_DENIED"
    end
    -- item 764
    return ok, result
end

function get_doc(data, user_id, roles)
    local ok, result
    -- item 73
    ok, result = get_doc_kernel(
        data.doc_id,
        user_id,
        roles
    )
    -- item 105
    if ok then
        -- item 435
        result.items = utils.map(
            db_get_items(data.doc_id),
            row_to_item
        )
        -- item 348
        if data.visit then
            -- item 351
            add_to_recent(
                data.doc_id,
                user_id
            )
        end
    end
    -- item 72
    return ok, result
end

function get_doc_kernel(doc_id, user_id, roles)
    local access, doc, doc_row, ok, result, tag_row
    -- item 1080
    doc_row = db_get_doc(doc_id)
    -- item 1091
    if doc_row then
        -- item 1103
        tag_row = db_get_tag_row(doc_id)
        -- item 1104
        if tag_row then
            -- item 1097
            doc = row_to_doc(doc_row)
            -- item 1105
            doc.space_id = tag_row[2]
            doc.tag = tag_row[3]
            -- item 1081
            access = space.get_space_access(
                doc.space_id,
                user_id,
                roles
            )
            -- item 1083
            if access then
                -- item 1095
                doc.access = access
                -- item 1096
                ok = true
                result = doc
            else
                -- item 1085
                ok = false
                result = "ERR_ACCESS_DENIED"
            end
        else
            -- item 1093
            ok = false
            result = "ERR_NOT_FOUND"
        end
    else
        -- item 1093
        ok = false
        result = "ERR_NOT_FOUND"
    end
    -- item 1079
    return ok, result
end

function get_latest_tag(space_id)
    local index, row
    -- item 630
    index = box.space.rtags.index.by_tag
    -- item 631
    row = index:max(space_id)
    -- item 632
    if (row) and (row[2] == space_id) then
        -- item 637
        return row[3]
    else
        -- item 635
        return nil
    end
end

function get_records(data, user_id, roles)
    local access, docs, fields, ok, result
    -- item 552
    access = space.get_space_access(
        data.space_id,
        user_id,
        roles
    )
    -- item 553
    if access then
        -- item 551
        docs = db_get_docs(data.space_id)
        -- item 557
        result = {records={}}
        for _, doc in ipairs(docs) do
            -- item 566
            fields = doc[3]
            -- item 563
            if fields.type == "record" then
                -- item 567
                table.insert(
                    result.records,
                    {name=fields.name}
                )
            end
        end
        -- item 562
        ok = true
    else
        -- item 555
        ok = false
        result = "ERR_ACCESS_DENIED"
    end
    -- item 561
    return ok, result
end

function get_tags(data, user_id, roles)
    local tag, tag_row
    -- item 307
    local result = {}
    for _, doc_id in ipairs(data.ids) do
        -- item 311
        tag_row = db_get_tag_row(doc_id)
        -- item 312
        if (tag_row) and (tag_row[4]) then
            -- item 316
            tag = tag_row[3]
        else
            -- item 545
            tag = "deleted"
        end
        -- item 315
        result[doc_id] = tag
    end
    -- item 317
    return true, result
end

function init()
    -- item 33
    module.handlers.get_doc = get_doc
    module.handlers.get_records = get_records
    module.handlers.insert_doc = insert_doc
    module.handlers.update_doc = update_doc
    module.handlers.delete_doc = delete_doc
    module.handlers.get_tags = get_tags
    module.handlers.edit = edit
    -- item 723
    module.handlers.get_all_live_tags = get_all_live_tags
    module.handlers.get_changes = get_changes
    -- item 837
    module.handlers.copy = copy
    module.handlers.move = move
end

function insert_doc(data, user_id, roles)
    local doc_id, ok, parent_id, ptag, result, space_id, tag, tags, write_ok
    -- item 671
    box.begin()
    -- item 292
    parent_id = data.fields.parent_id
    -- item 613
    write_ok, space_id = can_write(
        parent_id,
        user_id,
        roles
    )
    -- item 229
    if write_ok then
        -- item 236
        set_when_created(data.fields, user_id)
        -- item 644
        data.fields.parent_id = nil
        -- item 239
        doc_id, tag = db_insert_doc(
            space_id,
            parent_id,
            data.fields
        )
        -- item 328
        tags = {}
        tags[doc_id] = tag
        -- item 291
        ptag = tag_doc(parent_id, user_id)
        tags[parent_id] = ptag
        -- item 235
        ok = true
        result = {
        	doc_id=doc_id,
        	tags=tags
        }
    else
        -- item 232
        ok = false
        result = "ERR_ACCESS_DENIED"
    end
    -- item 672
    box.commit()
    -- item 233
    return ok, result
end

function make_key2(row)
    local key
    -- item 450
    key = {row[1], row[2]}
    -- item 451
    return key
end

function make_num_comparer(prop)
    -- item 1148
    return function(left, right)
    	return tonumber(left[prop]) < tonumber(right[prop])
    end
end

function make_tag(fields, user_id, now)
    local tag
    -- item 301
    tag = user_id .. tostring(now)
    -- item 327
    fields.tag = tag
    -- item 326
    return tag
end

function move(data, user_id, roles)
    local ok, result, tags, target_space
    -- item 854
    ok, target_space = can_write(
        data.target,
        user_id,
        roles
    )
    -- item 855
    result = nil
    -- item 852
    if ok then
        local normal_872
        normal_872 = 1
        for _, doc_id in ipairs(data.docs) do
            -- item 874
            ok = can_write(
                doc_id,
                user_id,
                roles
            )
            -- item 875
            if ok then
                
            else
                -- item 856
                ok = false
                result = "ERR_ACCESS_DENIED"
                normal_872 = 0
                break
            end
        end
        if normal_872 == 1 then
            local normal_861
            normal_861 = 1
            for _, doc_id in ipairs(data.docs) do
                -- item 864
                if find_cycle(doc_id, data.target) then
                    -- item 866
                    ok = false
                    result = "ERR_CYCLE"
                    normal_861 = 0
                    break
                end
            end
            if normal_861 == 1 then
                -- item 935
                tags = {}
                -- item 936
                tags[data.target] = tag_doc(
                    data.target,
                    user_id
                )
                for _, doc_id in ipairs(data.docs) do
                    -- item 870
                    db_move_doc(
                        doc_id,
                        data.target,
                        tags,
                        user_id
                    )
                end
                -- item 908
                result = {tags=tags}
            end
        end
    else
        -- item 856
        ok = false
        result = "ERR_ACCESS_DENIED"
    end
    -- item 857
    return ok, result
end

function parse_multipart(body)
    local body_lines, lines, separator, state, trimmed
    -- item 1052
    body_lines = {}
    -- item 1034
    state = "start"
    -- item 1031
    lines = utils.split(body, "\n")
    for _, line in ipairs(lines) do
        -- item 1044
        trimmed = utils.trim(line)
        -- item 10350001
        if state == "header" then
            -- item 1045
            if #trimmed == 0 then
                -- item 1047
                state = "body"
            end
        else
            -- item 10350002
            if state == "start" then
                -- item 1156
                log.info(trimmed)
                -- item 1153
                separator = trimmed .. "--"
                -- item 1154
                state = "header"
            else
                -- item 10350003
                if state == "body" then
                    
                else
                    -- item 10350004
                    error(state)
                end
                -- item 1050
                if (#trimmed == 0) or (trimmed == separator) then
                    break
                end
                -- item 1053
                table.insert(
                    body_lines,
                    trimmed
                )
            end
        end
    end
    -- item 1054
    return body_lines
end

function remove_from_recent(doc_id, user_id)
    local key
    -- item 346
    key = {doc_id, user_id}
    -- item 347
    box.space.rrecent:delete(key)
end

function row_to_doc(row)
    local doc
    -- item 251
    doc = row[3]
    -- item 252
    doc.doc_id = row[1]
    doc.parent_id = row[2]
    -- item 253
    return doc
end

function row_to_item(row)
    local item
    -- item 426
    item = row[3]
    -- item 428
    item.doc_id = row[1]
    item.item_id = row[2]
    -- item 427
    return item
end

function row_to_recent(row)
    local fields
    -- item 358
    fields = row[3]
    fields.user_id = row[2]
    fields.doc_id = row[1]
    -- item 359
    return fields
end

function set_when_created(fields, user_id)
    local now
    -- item 69
    now = utils.utc_time()
    -- item 58
    fields.when_created = now
    fields.created_by = user_id
    -- item 68
    fields.when_updated = now
    fields.updated_by = user_id
end

function set_when_updated(fields, user_id)
    local now
    -- item 71
    now = utils.utc_time()
    -- item 70
    fields.when_updated = now
    fields.updated_by = user_id
end

function tag_doc(doc_id, user_id)
    local changed_fields, new_row, old_row, tag
    -- item 280
    old_row = db_get_doc(doc_id)
    -- item 281
    if old_row then
        -- item 285
        changed_fields = old_row[3]
        -- item 290
        set_when_updated(changed_fields, user_id)
        -- item 283
        new_row = {
        	old_row[1],
        	old_row[2],
        	changed_fields
        }
        -- item 284
        box.space.rdocs:replace(new_row)
        -- item 661
        tag = tag_update(doc_id, true)
        -- item 321
        return tag
    else
        -- item 320
        return nil
    end
end

function tag_update(doc_id, exists)
    local rtags, space_id, tag, tag_row
    -- item 654
    rtags = box.space.rtags
    -- item 653
    tag_row = rtags:get(doc_id)
    -- item 655
    if tag_row then
        -- item 660
        space_id = tag_row[2]
        -- item 652
        tag = get_latest_tag(space_id) + 1
        -- item 658
        rtags:delete(doc_id)
        -- item 651
        rtags:insert {
        	doc_id,
        	space_id,
        	tag,
        	exists
        }
        -- item 650
        return tag
    else
        -- item 659
        return nil
    end
end

function update_doc(data, user_id, roles)
    local ok, result
    -- item 674
    box.begin()
    -- item 182
    if can_write(data.doc_id, user_id, roles) then
        -- item 194
        ok, result = db_update_doc(
            data.doc_id,
            data.fields,
            user_id
        )
    else
        -- item 185
        ok = false
        result = "ERR_ACCESS_DENIED"
    end
    -- item 673
    box.commit()
    -- item 186
    return ok, result
end

function upload_table_rows(doc_id, body, user_id, roles)
    local i, item_id, lines, ok, parts, result
    -- item 992
    if can_write(doc_id, user_id, roles) then
        -- item 1055
        lines = parse_multipart(body)
        -- item 1056
        box.begin()
        -- item 1058
        db_delete_items(doc_id)
        -- item 1064
        i = 1
        for _, line in ipairs(lines) do
            -- item 1061
            parts = utils.split(line, "|")
            -- item 1066
            body = {row=parts}
            -- item 1063
            item_id = tostring(i)
            -- item 1062
            db_insert_item(
                doc_id,
                item_id,
                body
            )
            -- item 1065
            i = i + 1
        end
        -- item 1057
        box.commit()
        -- item 996
        ok = true
        result = {}
    else
        -- item 994
        ok = false
        result = "ERR_ACCESS_DENIED"
    end
    -- item 995
    return ok, result
end


module.api = api
module.create_root_folder = create_root_folder
module.delete_recent_by_user = delete_recent_by_user
module.db_delete_doc = db_delete_doc
module.get_changes = get_changes
module.upload_table_rows = upload_table_rows
module.download_table_rows = download_table_rows

init()

return module
